branch-defaults:
  master:
    environment: Giteaprod-env
environment-defaults:
  Giteaprod-env:
    branch: null
    repository: null
global:
  application_name: gitea-prod
  default_ec2_keyname: gitlab-bastion
  default_platform: arn:aws:elasticbeanstalk:us-west-2::platform/Go 1 running on 64bit
    Amazon Linux 2/3.1.5
  default_region: us-west-2
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  sc: git
  workspace_type: Application
